language: ruby
rvm:
- 2.4.6
- 2.5.5
- 2.6.3
- jruby
- truffleruby
env:
  global:
  # api_key
  - secure: APwgfUKWYhBNNniPnVPbUN1nThch9YbXpahuRXyjgfly5RgfZew2g4OIDWHIS/ILhkylM3PpHZPEk02BVf65rPgvl/KZbv2FOM6DZRQ8QUr54gh9A5JwgfSc62t8fmFyzBMgOyJ5csS3f9rZUp8UuUBkCiWQsESqjytAFU35duPioiz1gkUwChcZ8A3Ap8sSYQeHadXdkfcd8fahFnbgHFRH6h7SuXqZIS5SwcMmJRem33HRfd6AImjI9p23H3C0/ajFIX/qrTlwIe+ZtvXJb3rjCjt6y/1chY91F3VDx2T2p4hs1qRcYYj8WQOTllum73arvtoACpLDU7ebe1lzWlC+GA7dUOjzvuwI8NzZGpaU15R0HEOAjctJFlnOF9H0XtvT95IcpVX99pVxzqA3DSdPlzTE5dBlJwFyMDNrjwrESLq2me58+R94ZYQa0hkmcGnBYn8UugRqsHycTRH8ZoCURqv8mFbRfAdAnESWE/dj/i66ptm7vnzHb0PRp9EVWQN2/M92eQ92/Sybu7qwNP5Zw7uQZAL/Vt4kswZCRrwVZ8dnsa2QAAZ2M51OrK9d4GyMn/nurWVE3GdZT/mXFbWz/40WA2+16u80128TDr0iWe882feTLJ3pTc6NZrwEPOIX98WtGl/yCOSWK5ulrDE99VYc+PB2IKa4N2T2Ca8=
  # sandbox token for testing
  - secure: Zw4NiLATccBhOBZJkYusHpuEDqbYfOddnedIZ5TEJLHuWUFHHwrB7ImIWoi3CcBuVn3oP9ra6GXHAE4P1AUFVpWEUjjHoyU9BnHWpPsbxqSf1yCkDcwiMqpcsV6MKA61cpKQQwsfl6PItH7udvYRZUchO8SOykv3ue34lQ8KXcOWMI/Y8jsZX8jZkapQjyHVI7fxZ4bM5GoS62eT2s3W6JCFiLyu38RVgx38V4XeKTI6aUX7KoYfBlzhMyX2RZffZ5d9yte1xuw0Rs9gq+iZi2jXuObs5NEHnNFJ8vBRTMPsHGezGEl3krDvQnE8qlk2AKoxQkf28YgLnpcpZZd0CZXm87tlB8dynLA8XeEmx0pKUYmLk6n2t6smJJAVDD03J3XeRb2NrLhot11ZWYaXyp0hzXfxu1FaAPq9LSbA6hr4E1cBAi++eTxQAS8aPVaLQix3GzjsOY8wcJ/m9eJ6gHAwh6w4gPFntLymW0g4ug9mZLQxywJ7UFOrdmng9TD1mK26jV5/VQcuZ7qPJSverN6Au21gG5Bl41ahpPAzh/6CuaPhF3huW3WFhq/YmEMHMYfSiE9+KMORYv/Qv1uc+dRddASPC0yAtHmGKeEp7CH7DE6Svn5qc5pTr0NaBpBnDMKizkfeV/bPUKF3HB77wjEo7zfvX3nAC7HDj20NA3U=
deploy:
  provider: rubygems
  api_key:
    secure: APwgfUKWYhBNNniPnVPbUN1nThch9YbXpahuRXyjgfly5RgfZew2g4OIDWHIS/ILhkylM3PpHZPEk02BVf65rPgvl/KZbv2FOM6DZRQ8QUr54gh9A5JwgfSc62t8fmFyzBMgOyJ5csS3f9rZUp8UuUBkCiWQsESqjytAFU35duPioiz1gkUwChcZ8A3Ap8sSYQeHadXdkfcd8fahFnbgHFRH6h7SuXqZIS5SwcMmJRem33HRfd6AImjI9p23H3C0/ajFIX/qrTlwIe+ZtvXJb3rjCjt6y/1chY91F3VDx2T2p4hs1qRcYYj8WQOTllum73arvtoACpLDU7ebe1lzWlC+GA7dUOjzvuwI8NzZGpaU15R0HEOAjctJFlnOF9H0XtvT95IcpVX99pVxzqA3DSdPlzTE5dBlJwFyMDNrjwrESLq2me58+R94ZYQa0hkmcGnBYn8UugRqsHycTRH8ZoCURqv8mFbRfAdAnESWE/dj/i66ptm7vnzHb0PRp9EVWQN2/M92eQ92/Sybu7qwNP5Zw7uQZAL/Vt4kswZCRrwVZ8dnsa2QAAZ2M51OrK9d4GyMn/nurWVE3GdZT/mXFbWz/40WA2+16u80128TDr0iWe882feTLJ3pTc6NZrwEPOIX98WtGl/yCOSWK5ulrDE99VYc+PB2IKa4N2T2Ca8=
  gem: square.rb
  on:
    branch: master
    repo: square/square-ruby-sdk
